### PR TITLE
Require args to be not empty

### LINKED ISSUE #2: Empty environment variables make the replicator exit with code 0
When I set a bad value in a `docker-compose` and that resolves to an empty string, the replicator starts and quietly exits with code 0. Expected behaviour is for the replicator to treat empty strings as non-existent and exit with a message and code != 0.

Example to reproduce, assuming `XXX` is not set:
```
  influx-replicator:
    image: ghcr.io/foundation-zero/influx-replicator:main
    depends_on:
      - influxdb
    environment:
      INFLUXDB_SOURCE_URL: ${INFLUXDB_SOURCE_URL}
      INFLUXDB_SOURCE_ORGANISATION: ${INFLUXDB_SOURCE_ORGANISATION}
      INFLUXDB_SOURCE_TOKEN: ${INFLUXDB_SOURCE_TOKEN}
      INFLUXDB_SOURCE_BUCKET: ${INFLUXDB_SOURCE_BUCKET}
      INFLUXDB_SINK_URL: ${INFLUXDB_SINK_URL}
      INFLUXDB_SINK_ORGANISATION: ${INFLUXDB_SINK_ORGANISATION}
      INFLUXDB_SINK_TOKEN: ${INFLUXDB_SINK_TOKEN}
      INFLUXDB_SINK_BUCKET: ${XXX}
```

### PR DESCRIPTION
**Pull request by Boudewijn26**
Fix #2

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -33,22 +33,22 @@ use bytes::BufMut;
 #[derive(Parser, Debug, Clone)]
 #[command(author, version, about, long_about=None)]
 struct Args {
-    #[arg(env = "INFLUXDB_SOURCE_URL")]
+    #[arg(env = "INFLUXDB_SOURCE_URL", value_parser = clap::builder::NonEmptyStringValueParser::new())]
```
Comment (Boudewijn26) [inline src/main.rs:36]: As per https://docs.rs/clap/latest/clap/_tutorial/chapter_3/index.html

**Review by kjkoster — APPROVED** [review]
